-- MySQL Script generated by MySQL Workbench
-- Wed Jun 10 11:31:51 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`Tadministrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Tadministrador` (
  `nC_AdministradorID` INT NOT NULL,
  `cNombre` VARCHAR(10) NOT NULL,
  `cApellido1` VARCHAR(15) NOT NULL,
  `cApellido2` VARCHAR(15) NOT NULL,
  `cGrupo` VARCHAR(10) NOT NULL,
  `cCurso` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`nC_AdministradorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`TAutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`TAutor` (
  `nC_AutorID` INT NOT NULL,
  `cNombre` VARCHAR(20) NOT NULL,
  `cApellido` VARCHAR(20) NOT NULL,
  `cDescripcion` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`nC_AutorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`TTematica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`TTematica` (
  `nC_TematicaID` INT NOT NULL,
  `Tema` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`nC_TematicaID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`TEditorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`TEditorial` (
  `nC_EditorialID` INT NOT NULL,
  `Tema` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`nC_EditorialID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`TPais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`TPais` (
  `nC_PaisID` INT NOT NULL,
  `cPais` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`nC_PaisID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`TLibro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`TLibro` (
  `cISBNID` INT NOT NULL,
  `cTitulo` VARCHAR(20) NOT NULL,
  `Tadministrador_nC_AdministradorID` INT NOT NULL,
  `TEditorial_nC_EditorialID` INT NOT NULL,
  PRIMARY KEY (`cISBNID`),
  INDEX `fk_TLibro_Tadministrador_idx` (`Tadministrador_nC_AdministradorID` ASC) VISIBLE,
  INDEX `fk_TLibro_TEditorial1_idx` (`TEditorial_nC_EditorialID` ASC) VISIBLE,
  CONSTRAINT `fk_TLibro_Tadministrador`
    FOREIGN KEY (`Tadministrador_nC_AdministradorID`)
    REFERENCES `biblioteca`.`Tadministrador` (`nC_AdministradorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TLibro_TEditorial1`
    FOREIGN KEY (`TEditorial_nC_EditorialID`)
    REFERENCES `biblioteca`.`TEditorial` (`nC_EditorialID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`TEscrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`TEscrito` (
  `TLibro_cISBNID` INT NOT NULL,
  `TAutor_nC_AutorID` INT NOT NULL,
  PRIMARY KEY (`TLibro_cISBNID`, `TAutor_nC_AutorID`),
  INDEX `fk_TLibro_has_TAutor_TAutor1_idx` (`TAutor_nC_AutorID` ASC) VISIBLE,
  INDEX `fk_TLibro_has_TAutor_TLibro1_idx` (`TLibro_cISBNID` ASC) VISIBLE,
  CONSTRAINT `fk_TLibro_has_TAutor_TLibro1`
    FOREIGN KEY (`TLibro_cISBNID`)
    REFERENCES `biblioteca`.`TLibro` (`cISBNID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TLibro_has_TAutor_TAutor1`
    FOREIGN KEY (`TAutor_nC_AutorID`)
    REFERENCES `biblioteca`.`TAutor` (`nC_AutorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`TLibroTematica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`TLibroTematica` (
  `TLibro_cISBNID` INT NOT NULL,
  `TTematica_nC_TematicaID` INT NOT NULL,
  PRIMARY KEY (`TLibro_cISBNID`, `TTematica_nC_TematicaID`),
  INDEX `fk_TLibro_has_TTematica_TTematica1_idx` (`TTematica_nC_TematicaID` ASC) VISIBLE,
  INDEX `fk_TLibro_has_TTematica_TLibro1_idx` (`TLibro_cISBNID` ASC) VISIBLE,
  CONSTRAINT `fk_TLibro_has_TTematica_TLibro1`
    FOREIGN KEY (`TLibro_cISBNID`)
    REFERENCES `biblioteca`.`TLibro` (`cISBNID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TLibro_has_TTematica_TTematica1`
    FOREIGN KEY (`TTematica_nC_TematicaID`)
    REFERENCES `biblioteca`.`TTematica` (`nC_TematicaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`TPaisAutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`TPaisAutor` (
  `TPais_nC_PaisID` INT NOT NULL,
  `TAutor_nC_AutorID` INT NOT NULL,
  PRIMARY KEY (`TPais_nC_PaisID`, `TAutor_nC_AutorID`),
  INDEX `fk_TPais_has_TAutor_TAutor1_idx` (`TAutor_nC_AutorID` ASC) VISIBLE,
  INDEX `fk_TPais_has_TAutor_TPais1_idx` (`TPais_nC_PaisID` ASC) VISIBLE,
  CONSTRAINT `fk_TPais_has_TAutor_TPais1`
    FOREIGN KEY (`TPais_nC_PaisID`)
    REFERENCES `biblioteca`.`TPais` (`nC_PaisID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TPais_has_TAutor_TAutor1`
    FOREIGN KEY (`TAutor_nC_AutorID`)
    REFERENCES `biblioteca`.`TAutor` (`nC_AutorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
